spring.datasource.url=jdbc:postgresql://localhost:5432/DBJava
spring.datasource.username=student
spring.datasource.password=chocolatefrog
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.liquibase.change-log=classpath:liquibase/changelog-master.yml
spring.liquibase.enabled=true

server.port=8080